apiVersion: v1
kind: Secret
metadata:
  name: aura-secrets
  namespace: aura
type: Opaque
stringData:
  SECRET_KEY: "your-secret-key-here-change-in-production"
  POSTGRES_PASSWORD: "aura_secure_password"
  OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  JINA_API_KEY: "your-jina-api-key"
  REDIS_PASSWORD: "redis_secure_password"